import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import sharpModule from 'sharp';

// The project's bundler resolution types this default import as unknown;
// only the small surface used here is described.
type Meta = {
  width?: number;
  height?: number;
  format?: string;
  hasAlpha?: boolean;
};
type Raw = {
  toBuffer(options: { resolveWithObject: true }): Promise<{ data: Uint8Array }>;
};
type Sharp = (file: string) => {
  metadata(): Promise<Meta>;
  ensureAlpha(): { extractChannel(index: number): { raw(): Raw } };
};
const sharp = sharpModule as unknown as Sharp;

// Validates the terrace theme pack against docs/ARCHITECTURE.md. The stage
// consumes exactly this shape; a broken manifest must fail here, not on a phone.

const dir = path.resolve(import.meta.dirname, '../public/plates/terrace');
const manifestPath = path.join(dir, 'manifest.json');

type Rect = { x: number; y: number; w: number; h: number };
type Point = { x: number; y: number };
type Entry = {
  id: string;
  file: string;
  rect: Rect;
  depth: number;
  kind: string;
  anchor?: Point;
  ember?: Point;
  destination?: string;
  opacity?: number;
  route?: { amplitude?: number; period?: number };
  safeEdges?: string[];
  breeze?: { hold: number };
  files?: string[];
  caption?: { dx: number; dy: number };
  parts?: {
    body: { file: string; rect: Rect };
    disc: {
      file: string;
      centre: Point;
      radius: number;
      tilt: number;
      yaw: number;
    };
    arm: {
      file: string;
      rect: Rect;
      pivot: Point;
      restAngle: number;
      playAngle: number;
    };
  };
};
type Manifest = {
  version: number;
  canvas: { width: number; height: number };
  layers: Entry[];
  sprites: Entry[];
  established?: { rect: Rect; depth?: number };
};

const LAYER_KINDS = new Set(['static', 'drift', 'sea', 'flecks', 'breeze']);
const SPRITE_KINDS = new Set(['static', 'boat', 'gull', 'prop', 'player']);
const DESTINATIONS = ['journal', 'atlas', 'identify', 'records'];

function load(): Manifest {
  assert.ok(
    existsSync(manifestPath),
    'manifest.json is generated by scripts/plates/build-plates.mjs',
  );
  return JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
}

function checkEntry(
  entry: Entry,
  kinds: Set<string>,
  canvas: Manifest['canvas'],
  overscan = false,
) {
  assert.match(entry.id, /^[a-zA-Z][a-zA-Z0-9-]*$/, `${entry.id}: id`);
  assert.match(
    entry.file,
    /^[a-zA-Z][a-zA-Z0-9-]*\.png$/,
    `${entry.id}: file name`,
  );
  assert.ok(kinds.has(entry.kind), `${entry.id}: kind ${entry.kind}`);
  assert.ok(
    Number.isFinite(entry.depth) && entry.depth > 0,
    `${entry.id}: depth`,
  );
  const { x, y, w, h } = entry.rect;
  for (const v of [x, y, w, h])
    assert.ok(Number.isInteger(v), `${entry.id}: integer rect`);
  assert.ok(w > 0 && h > 0, `${entry.id}: positive rect`);
  if (overscan) {
    // Layers may overscan the canvas for parallax; they must still touch it.
    assert.ok(
      x < canvas.width && y < canvas.height && x + w > 0 && y + h > 0,
      `${entry.id}: rect touches the canvas`,
    );
  } else
    assert.ok(
      x >= 0 && y >= 0 && x + w <= canvas.width && y + h <= canvas.height,
      `${entry.id}: rect inside canvas`,
    );
  if (entry.safeEdges !== undefined)
    for (const edge of entry.safeEdges)
      assert.ok(
        ['top', 'right', 'bottom', 'left'].includes(edge),
        `${entry.id}: safeEdges value ${edge}`,
      );
  if (entry.opacity !== undefined)
    assert.ok(entry.opacity > 0 && entry.opacity <= 1, `${entry.id}: opacity`);
}

void test('manifest follows the contract schema', () => {
  const m = load();
  assert.equal(m.version, 1);
  assert.deepEqual(m.canvas, { width: 1024, height: 1536 });
  assert.ok(m.layers.length >= 8, 'sky through tree');
  const ids = new Set<string>();
  for (const layer of m.layers) {
    checkEntry(layer, LAYER_KINDS, m.canvas, true);
    assert.ok(!ids.has(layer.id), `duplicate id ${layer.id}`);
    ids.add(layer.id);
    if (layer.kind === 'breeze') {
      assert.ok(layer.anchor, `${layer.id}: breeze needs an anchor`);
      if (layer.breeze)
        assert.ok(layer.breeze.hold >= 0, `${layer.id}: breeze hold`);
      const a = layer.anchor!;
      assert.ok(
        a.x >= layer.rect.x && a.x <= layer.rect.x + layer.rect.w,
        'anchor x within rect',
      );
      assert.ok(
        a.y >= layer.rect.y && a.y <= layer.rect.y + layer.rect.h,
        'anchor y within rect',
      );
    }
  }
  const depthsFarToNear = m.layers.map((l) => l.depth);
  for (let i = 1; i < depthsFarToNear.length; i++)
    assert.ok(
      depthsFarToNear[i] <= depthsFarToNear[i - 1],
      'layers are ordered far to near',
    );
  assert.equal(m.layers[0].id, 'sky');
  assert.ok(
    m.layers.some((l) => l.kind === 'sea'),
    'a sea layer exists',
  );
  assert.ok(
    m.layers.some((l) => l.kind === 'breeze'),
    'a breeze layer exists',
  );

  const destinations: string[] = [];
  for (const sprite of m.sprites) {
    checkEntry(sprite, SPRITE_KINDS, m.canvas);
    assert.ok(!ids.has(sprite.id), `duplicate id ${sprite.id}`);
    ids.add(sprite.id);
    if (sprite.caption) {
      assert.ok(
        Number.isFinite(sprite.caption.dx) &&
          Number.isFinite(sprite.caption.dy),
        `${sprite.id}: caption offsets`,
      );
      assert.ok(
        sprite.kind === 'prop' || sprite.kind === 'player',
        `${sprite.id}: only props carry captions`,
      );
    }
    if (sprite.kind === 'player') {
      const parts = sprite.parts!;
      assert.ok(parts && parts.body && parts.arm, `${sprite.id}: player parts`);
      assert.equal(
        sprite.destination,
        'records',
        `${sprite.id}: player opens records`,
      );
      destinations.push(sprite.destination!);
      if (parts.disc) {
        assert.ok(
          parts.disc.radius > 0 && parts.disc.tilt >= 0 && parts.disc.tilt < 90,
          'disc geometry',
        );
        const c = parts.disc.centre;
        assert.ok(
          c.x > sprite.rect.x && c.x < sprite.rect.x + sprite.rect.w,
          'disc centre inside the body',
        );
      }
      const pv = parts.arm.pivot;
      assert.ok(
        pv.x >= parts.arm.rect.x && pv.x <= parts.arm.rect.x + parts.arm.rect.w,
        'arm pivot inside its rect',
      );
      assert.ok(
        pv.y >= parts.arm.rect.y && pv.y <= parts.arm.rect.y + parts.arm.rect.h,
        'arm pivot inside its rect',
      );
      assert.notEqual(parts.arm.restAngle, parts.arm.playAngle, 'arm swings');
    }
    if (sprite.kind === 'prop') {
      assert.ok(
        sprite.destination && DESTINATIONS.includes(sprite.destination),
        `${sprite.id}: destination`,
      );
      destinations.push(sprite.destination!);
      assert.ok(
        sprite.rect.w >= 120,
        `${sprite.id}: props stay tappable (≥120 canvas px wide)`,
      );
    } else if (sprite.kind !== 'player')
      assert.equal(
        sprite.destination,
        undefined,
        `${sprite.id}: only props open destinations`,
      );
    if (sprite.route) {
      assert.ok(
        sprite.route.amplitude! > 0 && sprite.route.period! > 0,
        `${sprite.id}: route`,
      );
    }
    if (sprite.ember) {
      const e = sprite.ember;
      assert.ok(
        e.x >= sprite.rect.x && e.x <= sprite.rect.x + sprite.rect.w,
        'ember x within its sprite',
      );
      assert.ok(
        e.y >= sprite.rect.y && e.y <= sprite.rect.y + sprite.rect.h,
        'ember y within its sprite',
      );
    }
  }
  assert.deepEqual(
    [...destinations].sort(),
    [...DESTINATIONS].sort(),
    'every destination has exactly one prop',
  );
  assert.ok(
    m.sprites.some((s) => s.ember),
    'an ember point exists for smoke and glow',
  );
  assert.ok(
    m.sprites.some((s) => s.kind === 'boat'),
    'a boat sprite exists',
  );
  const gull = m.sprites.find((s) => s.kind === 'gull');
  assert.ok(
    gull && gull.files && gull.files.length === 3,
    'one gull sprite with three wing frames (up, level, down)',
  );
  assert.equal(m.established, undefined, 'no established plaque in this theme');
  assert.equal(
    m.sprites.filter((s) => s.kind === 'boat').length,
    2,
    'two boats',
  );
});

void test('every referenced file exists, matches its rect and carries alpha', async () => {
  const m = load();
  let decodedBytes = 0;
  const seen = new Set<string>();
  for (const entry of [...m.layers, ...m.sprites]) {
    const extra = [...(entry.files ?? [])];
    if (entry.parts)
      extra.push(
        entry.parts.body.file,
        entry.parts.arm.file,
        ...(entry.parts.disc ? [entry.parts.disc.file] : []),
      );
    for (const name of extra) {
      const f = path.join(dir, name);
      assert.ok(existsSync(f), `${entry.id}: ${name} missing`);
      const em = await sharp(f).metadata();
      assert.equal(em.hasAlpha, true, `${entry.id}: ${name} alpha`);
      decodedBytes += em.width! * em.height! * 4;
      seen.add(name);
    }
    const file = path.join(dir, entry.file);
    assert.ok(existsSync(file), `${entry.id}: ${entry.file} missing`);
    const meta = await sharp(file).metadata();
    assert.equal(meta.format, 'png', `${entry.id}: png`);
    assert.equal(meta.width, entry.rect.w, `${entry.id}: width matches rect`);
    assert.equal(meta.height, entry.rect.h, `${entry.id}: height matches rect`);
    const isLayer = m.layers.includes(entry);
    // Layers may carry overscan margins for parallax; sprites never do.
    const maxW = isLayer ? 1280 : 1024,
      maxH = isLayer ? 1920 : 1536;
    assert.ok(
      meta.width! <= maxW && meta.height! <= maxH,
      `${entry.id}: file within ${maxW}×${maxH}`,
    );
    if (entry.id === 'sky') {
      assert.ok(
        entry.rect.x <= 0 &&
          entry.rect.y <= 0 &&
          entry.rect.x + entry.rect.w >= 1024 &&
          entry.rect.y + entry.rect.h >= 1536,
        'sky covers the whole canvas',
      );
    } else {
      assert.equal(meta.hasAlpha, true, `${entry.id}: alpha channel`);
      const { data } = await sharp(file)
        .ensureAlpha()
        .extractChannel(3)
        .raw()
        .toBuffer({ resolveWithObject: true });
      let opaque = 0;
      for (const v of data) if (v > 8) opaque++;
      assert.ok(opaque > 0, `${entry.id}: not empty`);
    }
    decodedBytes += meta.width! * meta.height! * 4;
    seen.add(entry.file);
  }
  assert.ok(
    decodedBytes < 80 * 1024 * 1024,
    `decoded RGBA ${(decodedBytes / 1048576).toFixed(1)} MB stays under 80 MB`,
  );
  assert.ok(
    seen.size >= m.layers.length + m.sprites.length,
    'each entry has its own file',
  );
});
