'use client';

import {
  useId,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent,
  type PointerEvent,
} from 'react';
import { ArrowLeft, ArrowRight, Leaf, Star } from 'lucide-react';
import type { CigarEntry } from '@/lib/types';
import { entryDate, statusOf } from '@/lib/lifecycle';
import { deckIndex, deckPage, deckSwipeDirection } from './journal-deck-state';
import './JournalDeck.css';

export function JournalDeck({
  entries,
  sample,
  onOpen,
}: {
  entries: CigarEntry[];
  sample: boolean;
  onOpen: (entry: CigarEntry) => void;
}) {
  const [activeId, setActiveId] = useState<string | null>(null);
  const [offset, setOffset] = useState(0);
  const [direction, setDirection] = useState(1);
  const drag = useRef<{
    pointer: number;
    x: number;
    y: number;
    axis: 'pending' | 'horizontal' | 'vertical';
  } | null>(null);
  const suppressClick = useRef(false);
  const hintId = useId();
  const index = deckIndex(
    entries.map((entry) => entry.id),
    activeId,
  );
  const entry = entries[index];
  if (!entry) return null;

  function turn(next: number) {
    const nextIndex = deckPage(index, next, entries.length);
    setDirection(next >= 0 ? 1 : -1);
    setOffset(0);
    if (nextIndex !== index) setActiveId(entries[nextIndex].id);
  }

  function pointerDown(event: PointerEvent<HTMLButtonElement>) {
    if (!event.isPrimary || event.button !== 0) return;
    suppressClick.current = false;
    drag.current = {
      pointer: event.pointerId,
      x: event.clientX,
      y: event.clientY,
      axis: 'pending',
    };
  }

  function pointerMove(event: PointerEvent<HTMLButtonElement>) {
    const start = drag.current;
    if (!start || start.pointer !== event.pointerId) return;
    const x = event.clientX - start.x;
    const y = event.clientY - start.y;
    if (start.axis === 'pending' && Math.max(Math.abs(x), Math.abs(y)) > 8) {
      start.axis = Math.abs(x) > Math.abs(y) * 1.2 ? 'horizontal' : 'vertical';
      if (start.axis === 'horizontal')
        event.currentTarget.setPointerCapture(event.pointerId);
    }
    if (start.axis !== 'horizontal') return;
    suppressClick.current = true;
    const limit = event.currentTarget.clientWidth * 0.4;
    setOffset(Math.max(-limit, Math.min(limit, x)));
  }

  function pointerEnd(event: PointerEvent<HTMLButtonElement>) {
    const start = drag.current;
    if (!start || start.pointer !== event.pointerId) return;
    drag.current = null;
    if (event.currentTarget.hasPointerCapture(event.pointerId))
      event.currentTarget.releasePointerCapture(event.pointerId);
    if (event.type !== 'pointercancel' && start.axis === 'horizontal') {
      const next = deckSwipeDirection(
        event.clientX - start.x,
        event.clientY - start.y,
        event.currentTarget.clientWidth,
      );
      if (next) turn(next);
    }
    setOffset(0);
    // Consume the click generated by this drag, not the next deliberate tap.
    window.setTimeout(() => {
      suppressClick.current = false;
    }, 0);
  }

  function keyboard(event: KeyboardEvent<HTMLButtonElement>) {
    if (event.key === 'ArrowLeft') turn(-1);
    else if (event.key === 'ArrowRight') turn(1);
    else if (event.key === 'Home') turn(-entries.length);
    else if (event.key === 'End') turn(entries.length);
    else return;
    event.preventDefault();
  }

  const date = new Date(`${entryDate(entry)}T12:00:00`).toLocaleDateString(
    undefined,
    { month: 'short', day: 'numeric', year: 'numeric' },
  );
  return (
    <div
      className="journal-deck"
      data-direction={direction}
      data-single={entries.length === 1}
    >
      <p id={hintId} className="visually-hidden">
        Swipe sideways or use the arrow keys to turn pages. Tap a page to open
        its details.
      </p>
      <div className="journal-deck-stack">
        <button
          type="button"
          className={`journal-deck-card ${offset ? 'is-dragging' : ''}`}
          style={
            {
              '--deck-drag': `${offset}px`,
              '--deck-tilt': `${offset / 28}deg`,
            } as CSSProperties
          }
          aria-label={`Open ${entry.fullName}`}
          aria-describedby={hintId}
          onPointerDown={pointerDown}
          onPointerMove={pointerMove}
          onPointerUp={pointerEnd}
          onPointerCancel={pointerEnd}
          onKeyDown={keyboard}
          onClick={() => {
            if (!suppressClick.current) onOpen(entry);
          }}
        >
          <span className="journal-deck-page" key={entry.id}>
            <span className="journal-deck-folio">
              {sample ? 'Sample page' : 'Field notes'}{' '}
              <span>{String(index + 1).padStart(2, '0')}</span>
            </span>
            <span
              className={`journal-deck-photo ${entry.photo ? '' : 'is-empty'}`}
            >
              {entry.photo ? (
                <img
                  src={entry.photo}
                  alt={
                    sample
                      ? 'Illustrative sample cigar photograph'
                      : `Your photograph of ${entry.fullName}`
                  }
                  draggable="false"
                />
              ) : (
                <Leaf size={34} strokeWidth={1.2} aria-hidden="true" />
              )}
            </span>
            <span className="journal-deck-writing">
              <span className="journal-deck-name">{entry.fullName}</span>
              <span className="journal-deck-origin">
                {entry.country || 'Origin not set'}
              </span>
              {statusOf(entry) === 'humidor' && (
                <span className="journal-deck-status">In the humidor</span>
              )}
              {entry.notes && (
                <span className="journal-deck-memory">{entry.notes}</span>
              )}
              <span className="journal-deck-baseline">
                <span>
                  {statusOf(entry) === 'humidor' ? 'Added ' : ''}
                  {date}
                </span>
                {statusOf(entry) !== 'humidor' && (
                  <span
                    className="journal-deck-stars"
                    aria-label={
                      entry.rating
                        ? `${entry.rating} out of 5 stars`
                        : 'Not rated'
                    }
                  >
                    {[1, 2, 3, 4, 5].map((star) => (
                      <Star
                        key={star}
                        size={15}
                        className={star <= entry.rating ? 'filled' : ''}
                        aria-hidden="true"
                      />
                    ))}
                  </span>
                )}
              </span>
            </span>
          </span>
          <span className="journal-deck-corner" aria-hidden="true" />
        </button>
      </div>
      <div className="journal-deck-navigation">
        <button
          type="button"
          onClick={() => turn(-1)}
          disabled={index === 0}
          aria-label="Previous cigar"
        >
          <ArrowLeft size={19} />
        </button>
        <output aria-live="polite" aria-atomic="true">
          {index + 1} <span>/</span> {entries.length}
        </output>
        <button
          type="button"
          onClick={() => turn(1)}
          disabled={index === entries.length - 1}
          aria-label="Next cigar"
        >
          <ArrowRight size={19} />
        </button>
      </div>
    </div>
  );
}
