/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.api.jsonc --include-runtime=false --env-interface=EmberWorkerEnv worker/bindings.d.ts` (hash: 3bba10ba8bcc7fe01113b929bcee324c)
interface __BaseEnv_EmberWorkerEnv {
	OPENAI_MODEL: "gpt-4.1-mini";
	OPENAI_API_KEY: string;
	EMBER_DEVICE_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_EmberWorkerEnv {}
}
interface EmberWorkerEnv extends __BaseEnv_EmberWorkerEnv {}
